### Register a TRADER
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "name": "kiranreddy",
    "email": "kiran@gmail.com",
    "password": "kiran",
    "role": "TRADER"
}

### Login as TRADER
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "vinya@gmail.com",
    "password": "vinya"
}

### Login as ADMIN
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "manoj@gmail.com",
    "password": "manoj"
}

### Logout
GET http://localhost:5000/auth/logout
