### Get user profile
GET http://localhost:5000/user-api/users/69f8a710341e20906c127433

### Get user balance
GET http://localhost:5000/user-api/users/balance/69f8a710341e20906c127433

### Update user profile
PUT http://localhost:5000/user-api/users/69f8a710341e20906c127433
Content-Type: application/json

{
    "name": "Vinya Updated",
    "email": "vinya@gmail.com"
}

### Change password
PUT http://localhost:5000/user-api/users/change-password/69f8a710341e20906c127433
Content-Type: application/json

{
    "currentPassword": "vinya1",
    "newPassword": "vinya"
}

### Add funds to wallet
POST http://localhost:5000/user-api/add-funds
Content-Type: application/json

{
    "userId": "69f8a710341e20906c127433",
    "amount": 5000
}

### Get trader dashboard
GET http://localhost:5000/user-api/dashboard/69f8a710341e20906c127433