### Register a TRADER
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "name": "Vinya",
    "email": "vinya@gmail.com",
    "password": "vinya123",
    "role": "TRADER"
}

### Login as TRADER
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "vinya@gmail.com",
    "password": "vinya123"
}

### Login as ADMIN
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "manoj@gmail.com",
    "password": "manoj"
}

### Logout
GET http://localhost:5000/auth/logout
