### ALERT ROUTES
### Login as TRADER first

### Get user's alerts (active + triggered)
GET http://localhost:5000/user-api/alerts/69f8a710341e20906c127433

### Create alert — notify when stock goes ABOVE target
POST http://localhost:5000/user-api/alerts
Content-Type: application/json

{
    "userId": "69f8a710341e20906c127433",
    "stockId": "69f97cfb83274caa64ef30cf",
    "targetPrice": 2600,
    "direction": "ABOVE"
}

### Create alert — notify when stock goes BELOW target
POST http://localhost:5000/user-api/alerts
Content-Type: application/json

{
    "userId": "69f8a710341e20906c127433",
    "stockId": "69f97cfb83274caa64ef30cf",
    "targetPrice": 2400,
    "direction": "BELOW"
}

###ERROR: Duplicate alert
POST http://localhost:5000/user-api/alerts
Content-Type: application/json

{
    "userId": "69f8a710341e20906c127433",
    "stockId": "69f97cfb83274caa64ef30cf",
    "targetPrice": 2600,
    "direction": "ABOVE"
}

### ERROR: Invalid direction
POST http://localhost:5000/user-api/alerts
Content-Type: application/json

{
    "userId": "69f8a710341e20906c127433",
    "stockId": "69f97cfb83274caa64ef30cf",
    "targetPrice": 3000,
    "direction": "SIDEWAYS"
}

### Delete an alert (replace <ALERT_ID>)
DELETE http://localhost:5000/user-api/alerts/69fabdc0dc744851abd1d63f

### --- TRIGGER TEST ---
### Step 1: Create an ABOVE alert for price 2600
### Step 2: Login as ADMIN (use req-auth.http)
### Step 3: Update stock price to 2650 (use req-stock.http)
### Step 4: Check alerts again — it should show as triggered
GET http://localhost:5000/user-api/alerts/69fabdc0dc744851abd1d63f
