### user profile
GET http://localhost:5000/user-api/users

### get balance
GET http://localhost:5000/user-api/users/balance/69f85dcae549633c0e54922c

### update profile
PUT http://localhost:5000/user-api/users/69f85dcae549633c0e54922c
Content-Type: application/json

{
    "name":"vinya reddy",
    "email":"vinya@gmail.com"
}